### ISSUE TITLE
detection of wide transponder

### ISSUE THREAD

**Issue by psyborg55** [deeptho/neumodvb#24]
neumodvb detects 70mhz transponder at 7e, and it appears to be wrong detection
based on information from user with receiver capable of tuning these streams it's two transponders here close to each other
![Screenshot from 2022-08-19 23-31-55](https://user-images.githubusercontent.com/15853469/185695492-106342cd-4a8a-4be6-bd23-1406c039be56.png)

latest version makes no difference
![Screenshot from 2022-08-19 23-30-08](https://user-images.githubusercontent.com/15853469/185695594-5a1497db-62a9-46d2-8678-a4472918f8d9.png)

sometimes one of these appears to have better signal level
![Screenshot from 2022-08-19 23-38-40](https://user-images.githubusercontent.com/15853469/185695680-04387b9b-ca1a-408e-8072-bf8a6ca02181.png)

**Comment by deeptho** [comment]
I wouldn't read too much into the sloping spectrum. You see sloping at other frequencies as well, either due to incorrect/unstable 
AGC or because of other reasons.

Judging from the spectrum, there is no way to distinguish these transponders. I would be surprised if these were different transponders, but the signal is too weak to lock here.
Note that this mux has not always been there, so at some time it may just have been  two different muxes or it could indeed
be some weard combination of two muxes

**Comment by psyborg55** [comment]
True, it's not always there. Seems like an occasional feed.
According to info it is NS3/NS4 which seems to be further extended s2x format.
Maybe if you have very high resolution s2x card it is possible to see if there is a split in the middle of it.
The format also may use rolloff factor 0.02 and it could be a reason two transponders appear as one on non-supported spectrum analyzers

**Comment by deeptho** [comment]
2% of 100 Mhz is still 2Mhz and should be clearly visible on your card and certainly on tbs6909x which has 50kHz resolution.

**Comment by psyborg55** [comment]
That makes no sense to me. A DVBS transponder edges would occupy 2x35mhz by that logic.

**Comment by deeptho** [comment]
No: bandwith = symbolrate (1+rolloff)
1+roloff=1.35 for dvbs.
 
If two 100Mhz channels are next to each other then there must be a gap of approx
2% of the bandwidth (2% =0.02). In this example 2MHz. Otherwise the muxes would 
overlap. I guess the service provider would try to avoid that.

Or did I make a mistake somewhere?

**Comment by psyborg55** [comment]
I think it's not about the gap between the two transponders at all. Rather about width of the signal on edge where it drops from ~peak value down to the level where it disappear below noise floor.
If the muxes overlap by just a little it may not cause issue at all with their reception and still be enough to cause a confusion about width

**Comment by psyborg55** [comment]
Couldn't get any kind of lock with center freq at 1/4 or 3/4 of the peak width. Based on other NS3/NS4 mux width of approx 30000 (34288) that i managed to get partial lock it appears the report was wrong and this was single channel.

**Comment by deeptho** [comment]
Of course rolloff is about the drop down, but i think it would not make a lot of sense to have spectra from the same satellite overlap.

See for example TR 102 376 2 (it does not say that it has to be so...)

Transponder Frequency spacing, is the distance of center frequency of adjacent transponders. For example, for
36 MHz transponders a spacing of 40 MHz may be used. Throughout the present document it will be assumed
that for any nominal transponder/beam bandwidth, the spacing is set to 40/36 = 1,11 times the nominal
bandwidth.
