### ISSUE TITLE
Invalid window

### ISSUE THREAD

**Issue by andimik** [deeptho/neumodvb#35]
Using Ubuntu 23.10 (brand now installation including your drivers for TBS6903x) I sometimes get a gtk-window for just around 1 second. It will then terminate saying,

> $ LANG=C ./neumodvb.py 
loading options from /home/andreas/apps/neumodvb/config/neumodvb.cfg
loading options from /etc/neumodvb/neumodvb.cfg
>
> (neumodvb.py:37686): Gtk-CRITICAL **: 11:48:45.994: gtk_widget_set_name: assertion 'GTK_IS_WIDGET (widget)' failed
Bus-Zugriffsfehler (Speicherabzug geschrieben)

and 

> Invalid window subscriber_pybind.cc:85

in the log file, which comes from

https://github.com/deeptho/neumodvb/blob/86fff4dbfea8365b60cc320365fe1baceb6c0023/src/receiver/subscriber_pybind.cc#L85

[neumo.log](https://github.com/deeptho/neumodvb/files/13538646/neumo.log)

Maybe it has to do with NVIDIA problem as I was starting Ubuntu with `acpi=noirq`?

I will try again with other boot parameters.

**Comment by deeptho** [comment]
Sounds like some initialisation code is run before a widget is ready. The problem is that all of these 
underlying libraries are quite buggy.

You could try to check for null pointers in subscriber_py_bind.cc by replacing set_gtk_window_name
with the following code and then report what happens.

static void set_gtk_window_name(py::object window, const char* name) {
	auto* w = wxLoad<wxWindow>(window, "wxWindow");
	if(!w) {
		dterrorf("Could not set window name {}", name);
	} else {
		auto* x = w->GetHandle();
		if(!x) {
			dterrorf("Could not get handle for window {}", name);
		} else {
			gtk_widget_set_name(x, (const gchar*)name);
		}
	}
}

static void set_gtk_window_name(py::object window, const char* name) {
	auto* w = wxLoad<wxWindow>(window, "wxWindow");
   if(!
	auto* x = w->GetHandle();
	gtk_widget_set_name(x, (const gchar*)name);
}

**Comment by deeptho** [comment]
Probably fixed. Reopen if not
