### ISSUE TITLE
Disable autodiscovery

### ISSUE THREAD

**Issue by psyborg55** [deeptho/neumodvb#9]
Feature request to add posibilty to disable auto/network discovery.
It interferers in testing by forcing predefined values, so its hard to tell where the tuning/scanning problems happen

**Comment by deeptho** [comment]
I forgot to tell you, but instead of scanning a mux, just tune to it (ctrl-M). That will pull in si-data for the current mux 
only but will not tune to other muxes. 

Tuning parameters will still be updated for the current mux. I am afraid that maintaining two sets of tuning parameters
per mux will complicate the code too much. In most cases the SI information is the correct one and it is also used to
associate services and muxes. 

One option would be to add some fields for informational purposes only, which would be the last known tune parameters
which actually tuned the mux, another an option to disable si processing entirely. That would not be what most users want.

**Comment by psyborg55** [comment]
It shouldnt be disabled entirely, just configurable from GUI.
I thought it is simple change, as tvheadend does the same and it works perfectly there.
And i think there shouldnt be more than one set of tuning parameters, only difference it would make whether the parameters are obtained over the air, or entered manually by user into db

**Comment by deeptho** [comment]
It makes more difference than you think. neumodvb is not tvheadend. ll of these small changes tend to introduce
subtle bugs in other areas. It is still a useful feature. Perhaps later.

**Comment by deeptho** [comment]
Fixed
